name: fem-vanilla-js-go

services:
  dev:
    container_name: "fem-vanilla-js-go"
    image: "${IMAGE:-dimwittedmonkey}/dev-gopsql:latest"
    volumes:
      - "${SOURCE:-~/src}:/workspace"
      - "${SSH:-~/.ssh}:/home/neodev/.ssh"
    ports:
      - "8081:8081"
    restart: unless-stopped
